# Generated by Django 5.2.17 on 2026-09-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens', '0005_fotos_no_isolamento'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoDeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destino', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=200)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('erro', models.TextField(blank=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='ordens.eventoos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'aviso ao cliente',
                'verbose_name_plural': 'avisos ao cliente',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'enviado_em'], name='avisos_avis_tenant__1f4d38_idx')],
            },
        ),
    ]
