# Generated by Django 5.2.17 on 2026-10-02 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mes', models.DateField(help_text='Primeiro dia do mês em que o custo foi pago.')),
                ('descricao', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_lancados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custo da plataforma',
                'verbose_name_plural': 'custos da plataforma',
                'ordering': ['-mes', 'criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='custo_positivo')],
            },
        ),
    ]
