# Generated by Django 5.2.17 on 2026-09-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(choices=[('senha_vista', 'Senha de desbloqueio consultada'), ('senha_negada', 'Consulta à senha negada'), ('senha_purgada', 'Senha de desbloqueio removida')], max_length=30)),
                ('objeto', models.CharField(max_length=40)),
                ('objeto_id', models.PositiveBigIntegerField()),
                ('detalhe', models.CharField(blank=True, max_length=200)),
                ('origem', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_de_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', '-criado_em'], name='auditoria_r_tenant__a4adff_idx'), models.Index(fields=['objeto', 'objeto_id'], name='auditoria_r_objeto_aa61c0_idx')],
            },
        ),
    ]
