# Generated by Django 5.2.17 on 2026-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditoria_no_isolamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeauditoria',
            name='acao',
            field=models.CharField(choices=[('senha_vista', 'Senha de desbloqueio consultada'), ('senha_negada', 'Consulta à senha negada'), ('senha_purgada', 'Senha de desbloqueio removida'), ('usuario_criado', 'Usuário criado'), ('usuario_alterado', 'Usuário alterado'), ('senha_redefinida', 'Senha de acesso redefinida')], max_length=30),
        ),
    ]
