# Generated by Django 5.2.17 on 2026-10-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_acao_de_pagamento_removido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeauditoria',
            name='acao',
            field=models.CharField(choices=[('senha_vista', 'Senha de desbloqueio consultada'), ('senha_negada', 'Consulta à senha negada'), ('senha_purgada', 'Senha de desbloqueio removida'), ('usuario_criado', 'Usuário criado'), ('usuario_alterado', 'Usuário alterado'), ('senha_redefinida', 'Senha de acesso redefinida'), ('assistencia_criada', 'Assistência criada'), ('assistencia_alterada', 'Dados da assistência alterados'), ('convite_criado', 'Convite para a equipe criado'), ('convite_cancelado', 'Convite para a equipe cancelado'), ('link_compartilhado', 'Link de acompanhamento compartilhado'), ('pagamento_removido', 'Pagamento removido'), ('assinatura_contratada', 'Assinatura contratada'), ('assinatura_cancelada', 'Assinatura cancelada')], max_length=30),
        ),
    ]
