# Generated by Django 5.2.17 on 2026-09-22 18:42

import bancada.ordens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_status', models.CharField(blank=True, max_length=30)),
                ('para_status', models.CharField(max_length=30)),
                ('nota', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento da ordem',
                'verbose_name_plural': 'eventos da ordem',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço')], default='peca', max_length=10)),
                ('descricao', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'item do orçamento',
                'verbose_name_plural': 'itens do orçamento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_diagnostico', 'Em diagnóstico'), ('orcamento_enviado', 'Orçamento enviado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_reparo', 'Em reparo'), ('aguardando_peca', 'Aguardando peça'), ('pronto', 'Pronto'), ('entregue', 'Entregue'), ('devolvido_sem_reparo', 'Devolvido sem reparo')], default='recebido', max_length=30)),
                ('problema_relatado', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('laudo', models.TextField(blank=True)),
                ('token_publico', models.CharField(default=bancada.ordens.models.gerar_token_publico, editable=False, max_length=24, unique=True)),
                ('prometida_para', models.DateField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('garantia_ate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ['-criado_em'],
            },
        ),
    ]
