# Generated by Django 5.2.17 on 2026-09-22 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('ordens', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aparelho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='clientes.aparelho'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='tenants.loja'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='eventoos',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ordens.ordemservico'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['tenant', 'status'], name='ordens_orde_tenant__50a37d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['token_publico'], name='ordens_orde_token_p_4938d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero'), name='numero_unico_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='eventoos',
            index=models.Index(fields=['ordem', 'criado_em'], name='ordens_even_ordem_i_919f51_idx'),
        ),
    ]
