# Generated by Django 5.2.17 on 2026-09-23 12:06

import bancada.ordens.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_isolamento_no_banco'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('momento', models.CharField(choices=[('entrada', 'Na entrada'), ('saida', 'Na entrega')], default='entrada', max_length=10)),
                ('arquivo', models.ImageField(upload_to=bancada.ordens.models.caminho_da_foto)),
                ('legenda', models.CharField(blank=True, max_length=140)),
                ('largura', models.PositiveIntegerField()),
                ('altura', models.PositiveIntegerField()),
                ('visivel_ao_cliente', models.BooleanField(default=True)),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_enviadas', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.ordemservico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'foto da ordem',
                'verbose_name_plural': 'fotos da ordem',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['ordem', 'momento'], name='ordens_foto_ordem_i_cb7502_idx')],
            },
        ),
    ]
