# Generated by Django 5.2.17 on 2026-09-25 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('ordens', '0005_fotos_no_isolamento'),
        ('tenants', '0004_orientacao_ao_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['recebido_em', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(('valor_cobrado__gte', 0)), name='valor_cobrado_nao_negativo'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['tenant', 'recebido_em'], name='ordens_paga_tenant__b4618b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pagamento_com_valor_positivo'),
        ),
    ]
