# Generated by Django 5.2.17 on 2026-09-22 18:42

import bancada.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=80)),
                ('cor', models.CharField(blank=True, max_length=40)),
                ('imei', models.CharField(blank=True, max_length=20)),
                ('senha_desbloqueio', bancada.core.fields.CampoCriptografado(blank=True, default='')),
            ],
            options={
                'verbose_name': 'aparelho',
                'verbose_name_plural': 'aparelhos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=140)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('documento', models.CharField(blank=True, max_length=14)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
