# Generated by Django 5.2.17 on 2026-09-24 12:56

import bancada.tenants.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('papel', models.CharField(choices=[('dono', 'Dono'), ('tecnico', 'Técnico'), ('atendente', 'Atendente')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(default=bancada.tenants.models.gerar_token_de_convite, max_length=64, unique=True)),
                ('expira_em', models.DateTimeField(default=bancada.tenants.models.validade_padrao_do_convite)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'convite',
                'verbose_name_plural': 'convites',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='versao_dos_termos',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='email_unico_entre_usuarios', violation_error_message='Já existe uma conta com esse e-mail.'),
        ),
        migrations.AddField(
            model_name='convite',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convite',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='convite',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convite_de_origem', to=settings.AUTH_USER_MODEL),
        ),
    ]
