# Generated by Django 5.2.17 on 2026-09-25 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_convites_no_isolamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiros_passos_escondidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tours_vistos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
