# Generated by Django 5.2.17 on 2026-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0004_orientacao_ao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='da_plataforma',
            field=models.BooleanField(default=False, verbose_name='conta da plataforma'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último acesso'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('da_plataforma', False), models.Q(('papel', ''), ('tenant__isnull', True)), _connector='OR'), name='conta_da_plataforma_fora_das_assistencias', violation_error_message='A conta da plataforma não pertence a nenhuma assistência.'),
        ),
    ]
