# Generated by Django 5.2.17 on 2026-10-06 13:59

import bancada.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_conta_da_plataforma_e_ultimo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_altura', upload_to=bancada.tenants.models.caminho_da_logo, width_field='logo_largura'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_altura',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_largura',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
