# Generated by Django 5.2.17 on 2026-10-02 17:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_orientacao_ao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDoProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no_provedor', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(max_length=60)),
                ('conteudo', models.JSONField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento do provedor de cobrança',
                'verbose_name_plural': 'eventos do provedor de cobrança',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(choices=[('teste', 'Em teste grátis'), ('ativa', 'Ativa'), ('inadimplente', 'Pagamento atrasado'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='teste', max_length=20)),
                ('teste_termina_em', models.DateField()),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('documento_do_pagador', models.CharField(blank=True, max_length=14)),
                ('cliente_no_provedor', models.CharField(blank=True, max_length=60)),
                ('assinatura_no_provedor', models.CharField(blank=True, db_index=True, max_length=60)),
                ('assinada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('acesso_ate', models.DateField(blank=True, null=True)),
                ('avisos_de_fim_do_teste', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_no_provedor', models.CharField(max_length=60, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vencimento', models.DateField()),
                ('situacao', models.CharField(choices=[('aberta', 'Aguardando pagamento'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('estornada', 'Estornada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('forma_de_pagamento', models.CharField(blank=True, choices=[('', 'A escolher'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão')], max_length=20)),
                ('paga_em', models.DateField(blank=True, null=True)),
                ('link_de_pagamento', models.URLField(blank=True, max_length=300)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='assinaturas.assinatura')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-vencimento'],
            },
        ),
    ]
