# Generated by Django 5.2.17 on 2026-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_teste_para_as_assistencias_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
